# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.11.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_version: 10.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Addons concerning Odoo Italian Localization.
repo_name: Odoo Italia Modules
repo_slug: l10n-italy
repo_website: https://github.com/OCA/l10n-italy
travis_apt_packages: []
travis_apt_sources: []

