from . import pos_payment
from . import pos_payment_method
from . import point_of_sale
from . import account
from . import account_journal
from . import pos_order
from . import pos_session
from . import res_config_settings
from . import hr_employee
