# Copyright 2024 Lorenzo Battistini
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).

from odoo import api, models


class AccountTax(models.Model):
    _inherit = "account.tax"

    # Tax journal items are generated by the tax computation engine, not
    # copied from invoice lines.  The engine uses a "grouping key" dict to
    # decide which tax lines to merge (same key → same journal item) and
    # the dict values are then written as field values on the resulting
    # journal item.  The standard key does not include start_date/end_date,
    # so without these overrides dates from the source invoice line are lost.
    #
    # _prepare_base_line_grouping_key is used by _sync_tax_lines to build
    # the list of tracked fields on base (invoice) lines: adding dates here
    # ensures that changing start_date/end_date triggers a tax-line
    # recomputation (otherwise dates set after tax_ids would be ignored).
    #
    # _prepare_base_line_tax_repartition_grouping_key is called when
    # creating tax lines from invoice lines: adding the dates to the key
    # causes them to be written on the tax journal item and also keeps
    # invoice lines with different date ranges on separate tax lines.
    #
    # _prepare_tax_line_repartition_grouping_key is called when reconciling
    # existing tax lines during recomputation: it must return a matching key
    # so Odoo can update existing lines instead of deleting/re-creating them.
    #
    # We only propagate dates for repartition lines without account_id
    # (non-deductible portion that goes to the expense account).  Deductible
    # portions (with their own VAT credit account) do not carry dates
    # because they represent a tax credit, not a cost attributable to a
    # service period.

    @api.model
    def _prepare_base_line_grouping_key(self, base_line):
        grouping_key = super()._prepare_base_line_grouping_key(base_line)
        record = base_line["record"]
        grouping_key["start_date"] = record.start_date if record else False
        grouping_key["end_date"] = record.end_date if record else False
        return grouping_key

    @api.model
    def _prepare_base_line_tax_repartition_grouping_key(
        self, base_line, base_line_grouping_key, tax_data, tax_rep_data
    ):
        grouping_key = super()._prepare_base_line_tax_repartition_grouping_key(
            base_line, base_line_grouping_key, tax_data, tax_rep_data
        )
        tax_rep = tax_rep_data["tax_rep"]
        if not tax_rep.account_id:
            record = base_line["record"]
            grouping_key["start_date"] = record.start_date
            grouping_key["end_date"] = record.end_date
        else:
            # Explicitly reset dates inherited from base_line_grouping_key
            # (via **base_line_grouping_key spread in super): deductible
            # portions with their own account do not carry service-period dates.
            grouping_key["start_date"] = False
            grouping_key["end_date"] = False
        return grouping_key

    @api.model
    def _prepare_tax_line_repartition_grouping_key(self, tax_line):
        grouping_key = super()._prepare_tax_line_repartition_grouping_key(tax_line)
        tax_rep = tax_line["tax_repartition_line_id"]
        if not tax_rep.account_id:
            record = tax_line["record"]
            grouping_key["start_date"] = record.start_date
            grouping_key["end_date"] = record.end_date
        else:
            grouping_key["start_date"] = False
            grouping_key["end_date"] = False
        return grouping_key
